// <auto-generated />
namespace E_LearningWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCourseIdtoquestion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCourseIdtoquestion));
        
        string IMigrationMetadata.Id
        {
            get { return "201607271302477_Add CourseId to question"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
